remote_theme: broccolini/swiss
title: Test stastic
description: A tool to admin your jekyll sites
github_repo: jekyll
github_username: jekyll
social_link: twitter
social_username: jekyllrb
theme_color: black
